# _config.yml
title: "Iliyas Noman"
email: ""
description: "Researcher â€” short tagline here"
baseurl: ""   # leave empty for user site
url: "https://iliyasnoman.github.io"

theme: jekyll-theme-minimal
